spring.profiles.active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/ebook_chat
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis  
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
  redis:
    host: 192.168.99.100
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

flyway.enabled: true      
security.headers.cache: false 
server.session.timeout: 600

ebook:
  chat:
    relay:
      host: 192.168.99.100
      port: 61613

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/ebook_chat
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis
  redis:
    host: 192.168.99.100
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

flyway.enabled: true

ebook:
  chat:
    relay:
      host: 192.168.99.100
      port: 61613